# encoding: utf-8

# Begin Provisioning script
$script = <<SCRIPT

SCRIPT
# End Provisioning script


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: '33.33.33.15'
  config.vm.hostname = 'rogerworker'
  config.vm.define :rogerworker

  config.vm.synced_folder ".", '/home/worker'
  config.vm.synced_folder "../celery", '/celery'

  config.vm.provision "shell", inline: $script

  config.vm.provider :virtualbox do |v|
    opts = ['modifyvm', :id, '--memory', '512', '--natdnshostresolver1', 'on']
    v.customize opts
    v.name = "rogerworker"
  end

  config.vm.provider :vmware_fusion do |f|
    f.vmx['memsize'] = '512'
    f.vmx['displayname'] = "rogerworker"
  end
end
